services:
  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    container_name: minio
    ports:
      - '5010:9000'
      - '5011:9001'
    volumes:
      - './data/minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
  
  tag-files-service:
      build:
        context: ./tag-files-service
        dockerfile: Dockerfile
      container_name: tag-files-service
      ports:
        - '5001:8080'
      volumes:
        - './data:/app/data'
      depends_on:
        - minio
      environment:
        - 'ConnectionStrings__SQLite=Data Source=/app/data/tag-files.db'